"""Add past performance contract preferences and SAM registration fields

Revision ID: 361ffec74425
Revises: 001
Create Date: 2026-02-05 09:58:11.631092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '361ffec74425'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    # Add new columns as nullable first
    op.add_column('company_profiles', sa.Column('cage_code', sa.String(length=5), nullable=True))
    op.add_column('company_profiles', sa.Column('uei_number', sa.String(length=12), nullable=True))
    op.add_column('company_profiles', sa.Column('duns_number', sa.String(length=9), nullable=True))
    op.add_column('company_profiles', sa.Column('past_performance_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('company_profiles', sa.Column('priority_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('company_profiles', sa.Column('clearance_level', sa.String(length=20), nullable=True))
    op.add_column('company_profiles', sa.Column('contract_types_preference', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('company_profiles', sa.Column('open_to_subcontracting', sa.Boolean(), nullable=True))
    op.add_column('company_profiles', sa.Column('open_to_prime_contracting', sa.Boolean(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE company_profiles SET past_performance_keywords = '[]' WHERE past_performance_keywords IS NULL")
    op.execute("UPDATE company_profiles SET priority_keywords = '[]' WHERE priority_keywords IS NULL")
    op.execute("UPDATE company_profiles SET clearance_level = 'None' WHERE clearance_level IS NULL")
    op.execute("UPDATE company_profiles SET contract_types_preference = '[]' WHERE contract_types_preference IS NULL")
    op.execute("UPDATE company_profiles SET open_to_subcontracting = TRUE WHERE open_to_subcontracting IS NULL")
    op.execute("UPDATE company_profiles SET open_to_prime_contracting = TRUE WHERE open_to_prime_contracting IS NULL")
    
    # Now make them NOT NULL
    op.alter_column('company_profiles', 'past_performance_keywords', nullable=False)
    op.alter_column('company_profiles', 'priority_keywords', nullable=False)
    op.alter_column('company_profiles', 'clearance_level', nullable=False)
    op.alter_column('company_profiles', 'contract_types_preference', nullable=False)
    op.alter_column('company_profiles', 'open_to_subcontracting', nullable=False)
    op.alter_column('company_profiles', 'open_to_prime_contracting', nullable=False)
    op.alter_column('company_profiles', 'secondary_naics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('company_profiles', 'technical_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('company_profiles', 'industry_experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_profiles', 'certifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('company_profiles', 'target_contract_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_profiles', 'target_contract_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_profiles', 'preferred_agencies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('company_profiles', 'service_area',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('company_profiles', 'max_response_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_profiles', 'blacklist_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('company_profiles', 'requires_clearance',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('company_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_opportunities', 'relevance_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('saved_opportunities', 'user_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('saved_opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_history', 'total_results',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('search_history', 'high_relevance_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('search_history', 'medium_relevance_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('search_history', 'low_relevance_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('search_history', 'job_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('search_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'searches_this_month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'searches_this_month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('search_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('search_history', 'job_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('search_history', 'low_relevance_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('search_history', 'medium_relevance_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('search_history', 'high_relevance_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('search_history', 'total_results',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('saved_opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_opportunities', 'user_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('saved_opportunities', 'relevance_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_profiles', 'requires_clearance',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('company_profiles', 'blacklist_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('company_profiles', 'max_response_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company_profiles', 'service_area',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('company_profiles', 'preferred_agencies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('company_profiles', 'target_contract_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company_profiles', 'target_contract_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company_profiles', 'certifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('company_profiles', 'industry_experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company_profiles', 'technical_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('company_profiles', 'secondary_naics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('company_profiles', 'open_to_prime_contracting')
    op.drop_column('company_profiles', 'open_to_subcontracting')
    op.drop_column('company_profiles', 'contract_types_preference')
    op.drop_column('company_profiles', 'clearance_level')
    op.drop_column('company_profiles', 'priority_keywords')
    op.drop_column('company_profiles', 'past_performance_keywords')
    op.drop_column('company_profiles', 'duns_number')
    op.drop_column('company_profiles', 'uei_number')
    op.drop_column('company_profiles', 'cage_code')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
